- build: examples/1-wake
  photon: [0.6.3, 0.7.0, 1.0.0]
  p1: [1.0.0]
  electron: [0.6.4, 1.0.0]
  argon: [0.9.0]
  boron: [0.8.0-rc.27, 0.9.0]
  xenon: [0.9.0]
- build: examples/3-self-test
  argon: [0.9.0]
- build: examples/4-sram-test
  argon: [0.9.0]
- build: examples/5-eeprom-test
  argon: [0.9.0]
- build: examples/6-oscillator-trim
  argon: [0.9.0]
- build: examples/7-board-id-set
  argon: [0.9.0]
- build: examples/8-board-id
  argon: [0.9.0]

  